// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// f_md_cpp
double f_md_cpp(arma::vec v, arma::mat X, int n, int d, double h, double al, double C);
RcppExport SEXP _PPCI2_f_md_cpp(SEXP vSEXP, SEXP XSEXP, SEXP nSEXP, SEXP dSEXP, SEXP hSEXP, SEXP alSEXP, SEXP CSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type v(vSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type d(dSEXP);
    Rcpp::traits::input_parameter< double >::type h(hSEXP);
    Rcpp::traits::input_parameter< double >::type al(alSEXP);
    Rcpp::traits::input_parameter< double >::type C(CSEXP);
    rcpp_result_gen = Rcpp::wrap(f_md_cpp(v, X, n, d, h, al, C));
    return rcpp_result_gen;
END_RCPP
}
// df_md_cpp
arma::vec df_md_cpp(arma::vec v, arma::mat X, int n, int d, double h, double al, double C);
RcppExport SEXP _PPCI2_df_md_cpp(SEXP vSEXP, SEXP XSEXP, SEXP nSEXP, SEXP dSEXP, SEXP hSEXP, SEXP alSEXP, SEXP CSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type v(vSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type d(dSEXP);
    Rcpp::traits::input_parameter< double >::type h(hSEXP);
    Rcpp::traits::input_parameter< double >::type al(alSEXP);
    Rcpp::traits::input_parameter< double >::type C(CSEXP);
    rcpp_result_gen = Rcpp::wrap(df_md_cpp(v, X, n, d, h, al, C));
    return rcpp_result_gen;
END_RCPP
}
// ismin_cpp
int ismin_cpp(arma::vec v, arma::mat X, int n, int d, double h, double al, double C);
RcppExport SEXP _PPCI2_ismin_cpp(SEXP vSEXP, SEXP XSEXP, SEXP nSEXP, SEXP dSEXP, SEXP hSEXP, SEXP alSEXP, SEXP CSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type v(vSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type d(dSEXP);
    Rcpp::traits::input_parameter< double >::type h(hSEXP);
    Rcpp::traits::input_parameter< double >::type al(alSEXP);
    Rcpp::traits::input_parameter< double >::type C(CSEXP);
    rcpp_result_gen = Rcpp::wrap(ismin_cpp(v, X, n, d, h, al, C));
    return rcpp_result_gen;
END_RCPP
}
// md_b_cpp
double md_b_cpp(arma::vec v, arma::mat X, int n, int d, double h, double al, double C);
RcppExport SEXP _PPCI2_md_b_cpp(SEXP vSEXP, SEXP XSEXP, SEXP nSEXP, SEXP dSEXP, SEXP hSEXP, SEXP alSEXP, SEXP CSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type v(vSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type d(dSEXP);
    Rcpp::traits::input_parameter< double >::type h(hSEXP);
    Rcpp::traits::input_parameter< double >::type al(alSEXP);
    Rcpp::traits::input_parameter< double >::type C(CSEXP);
    rcpp_result_gen = Rcpp::wrap(md_b_cpp(v, X, n, d, h, al, C));
    return rcpp_result_gen;
END_RCPP
}
// ncut_x
double ncut_x(NumericVector x, double h, int n, int kmin);
RcppExport SEXP _PPCI2_ncut_x(SEXP xSEXP, SEXP hSEXP, SEXP nSEXP, SEXP kminSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type h(hSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type kmin(kminSEXP);
    rcpp_result_gen = Rcpp::wrap(ncut_x(x, h, n, kmin));
    return rcpp_result_gen;
END_RCPP
}
// dncut_x
NumericVector dncut_x(NumericVector x, double h, int n, int kmin);
RcppExport SEXP _PPCI2_dncut_x(SEXP xSEXP, SEXP hSEXP, SEXP nSEXP, SEXP kminSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type h(hSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type kmin(kminSEXP);
    rcpp_result_gen = Rcpp::wrap(dncut_x(x, h, n, kmin));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_PPCI2_f_md_cpp", (DL_FUNC) &_PPCI2_f_md_cpp, 7},
    {"_PPCI2_df_md_cpp", (DL_FUNC) &_PPCI2_df_md_cpp, 7},
    {"_PPCI2_ismin_cpp", (DL_FUNC) &_PPCI2_ismin_cpp, 7},
    {"_PPCI2_md_b_cpp", (DL_FUNC) &_PPCI2_md_b_cpp, 7},
    {"_PPCI2_ncut_x", (DL_FUNC) &_PPCI2_ncut_x, 4},
    {"_PPCI2_dncut_x", (DL_FUNC) &_PPCI2_dncut_x, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_PPCI2(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
